### ISSUE TITLE
display pdf instead of png images

### ISSUE THREAD

**Issue by Smirkey** [Anko59/aiden-job-finder#2]
currently pdfs are converted to png which is not necessary

**Comment by Anko59** [comment]
In theory it's easy: https://stackoverflow.com/questions/17784037/how-to-display-pdf-file-in-html

I'm just not sure if we should access user_data dir from the front end, or save the pdf in the static directory

**Comment by Anko59** [comment]
Tested and the display of pdf files is hard to setup and use correctly, it does not behave as an image but inserts and Iframe that calls google services to render the pdf
Sticking to pngs fro now
